// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:25490776191:web:ad170d6bfbdf0c882e5f4a',
    messagingSenderId: '25490776191',
    projectId: 'yacachatapp',
    authDomain: 'yacachatapp.firebaseapp.com',
    storageBucket: 'yacachatapp.firebasestorage.app',
    measurementId: 'G-47062804GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:25490776191:android:4214a8fe067ff98a2e5f4a',
    messagingSenderId: '25490776191',
    projectId: 'yacachatapp',
    storageBucket: 'yacachatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:25490776191:ios:76f3c22583860f5d2e5f4a',
    messagingSenderId: '25490776191',
    projectId: 'yacachatapp',
    storageBucket: 'yacachatapp.firebasestorage.app',
    iosBundleId: 'com.example.yaca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:25490776191:ios:76f3c22583860f5d2e5f4a',
    messagingSenderId: '25490776191',
    projectId: 'yacachatapp',
    storageBucket: 'yacachatapp.firebasestorage.app',
    iosBundleId: 'com.example.yaca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your key',
    appId: '1:25490776191:web:2cfcac6921c666062e5f4a',
    messagingSenderId: '25490776191',
    projectId: 'yacachatapp',
    authDomain: 'yacachatapp.firebaseapp.com',
    storageBucket: 'yacachatapp.firebasestorage.app',
    measurementId: 'G-WMVTSN8Q11',
  );
}
